import PptxGenJS from "pptxgenjs";
import { PresentationData, SlideContent, SlideType } from "../types";

export const generatePptx = async (
  data: PresentationData, 
  existingImages: Record<string, string>,
  imageGenerator: (prompt: string) => Promise<string | null>
) => {
  const pptx = new PptxGenJS();
  
  // Set Metadata
  pptx.author = 'PitchDeck AI';
  pptx.company = data.projectName;
  pptx.title = data.projectName + ' Pitch Deck';

  // Define Layouts
  pptx.layout = 'LAYOUT_16x9';

  // Add Master Slide (Branding)
  pptx.defineSlideMaster({
    title: 'MASTER_SLIDE',
    background: { color: 'FFFFFF' },
    objects: [
      {
        rect: { x: 0, y: 0, w: '100%', h: 0.15, fill: { color: '0F172A' } } // Top bar
      },
      {
        text: {
            text: 'CONFIDENTIAL - ' + data.projectName,
            options: { x: 0.5, y: 7.2, w: '50%', fontSize: 9, color: '94A3B8' }
        }
      },
      {
        text: {
            text: 'Generated by PitchDeck AI',
            options: { x: 10, y: 7.2, w: '20%', align: 'right', fontSize: 9, color: '94A3B8' }
        }
      }
    ]
  });

  // Iterate and create slides
  for (const slide of data.slides) {
    let visual = existingImages[slide.id];

    // If no image exists, try to generate it on the fly
    if (!visual) {
        try {
            const generated = await imageGenerator(slide.visualPrompt);
            if (generated) {
                visual = generated;
            }
        } catch (error) {
            console.warn(`Failed to auto-generate image for slide ${slide.id}`, error);
        }
    }
    
    // Ensure visual is string or undefined for the helper functions
    const visualData = visual || undefined;
    
    if (slide.type === SlideType.TITLE) {
        createTitleSlide(pptx, slide, visualData, data.tagline);
    } else if (slide.type === SlideType.PROBLEM || slide.type === SlideType.MARKET || slide.type === SlideType.VISION) {
        createEmphasisSlide(pptx, slide, visualData);
    } else {
        createContentSlide(pptx, slide, visualData);
    }
  }

  // Save the file
  const fileName = `${data.projectName.replace(/[^a-z0-9]/gi, '_')}_PitchDeck.pptx`;
  await pptx.writeFile({ fileName });
};

// --- Helper Functions for Layouts ---

const createTitleSlide = (pptx: PptxGenJS, slide: SlideContent, visual: string | undefined, tagline: string) => {
    const s = pptx.addSlide();
    
    // Background Image if available
    if (visual) {
        s.background = { data: visual };
        // Overlay to make text readable
        s.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: '100%', h: '100%', fill: { color: '0F172A', transparency: 30 } });
    } else {
        s.background = { color: '0F172A' };
    }

    s.addText(slide.title, {
        x: 1, y: 2.5, w: '80%',
        fontSize: 44, color: 'FFFFFF', bold: true, fontFace: 'Arial'
    });
    
    s.addText(tagline || slide.bullets[0], {
        x: 1, y: 3.8, w: '80%',
        fontSize: 20, color: 'E2E8F0', fontFace: 'Arial'
    });

    s.addText('PITCH DECK', {
        x: 1, y: 0.5,
        fontSize: 12, color: '4F46E5', bold: true, charSpacing: 3
    });
};

const createEmphasisSlide = (pptx: PptxGenJS, slide: SlideContent, visual: string | undefined) => {
    const s = pptx.addSlide({ masterName: 'MASTER_SLIDE' });
    
    // Title
    s.addText(slide.type, { x: 0.5, y: 0.8, fontSize: 10, color: '4F46E5', bold: true, charSpacing: 2 });
    s.addText(slide.title, { x: 0.5, y: 1.2, w: '40%', fontSize: 28, color: '0F172A', bold: true, fontFace: 'Times New Roman' });

    // Highlight Box
    if (slide.highlight) {
        s.addShape(pptx.ShapeType.rect, { x: 0.5, y: 5.5, w: 4, h: 1.2, fill: { color: 'F1F5F9' } });
        s.addText(slide.highlight, { x: 0.7, y: 5.6, w: 3.6, fontSize: 18, color: '4F46E5', bold: true });
    }

    // Bullets on the left
    const bullets = slide.bullets.map(b => ({ text: b, options: { fontSize: 14, color: '334155', breakLine: true, bullet: true } }));
    s.addText(bullets, { x: 0.5, y: 2.5, w: 4.5, h: 3, lineSpacing: 28 });

    // Visual on the right (Full height split)
    if (visual) {
        s.addImage({ data: visual, x: 5.5, y: 0.8, w: 7.83, h: 6.7 });
    } else {
        // Placeholder shape
        s.addShape(pptx.ShapeType.rect, { x: 5.5, y: 0.8, w: 7.83, h: 6.7, fill: { color: 'E2E8F0' } });
        s.addText("Visual: " + slide.visualPrompt, { x: 6, y: 3, w: 6, fontSize: 12, color: '64748B', align: 'center' });
    }
};

const createContentSlide = (pptx: PptxGenJS, slide: SlideContent, visual: string | undefined) => {
    const s = pptx.addSlide({ masterName: 'MASTER_SLIDE' });

    // Header
    s.addText(slide.type, { x: 0.5, y: 0.4, fontSize: 10, color: '4F46E5', bold: true, charSpacing: 2 });
    s.addText(slide.title, { x: 0.5, y: 0.7, w: '90%', fontSize: 24, color: '0F172A', bold: true, fontFace: 'Times New Roman' });

    // Content Grid
    // Left: Bullets
    const bullets = slide.bullets.map(b => ({ text: b, options: { fontSize: 16, color: '334155', breakLine: true, bullet: { type: 'bullet', code: '2022' } } }));
    s.addText(bullets, { x: 0.5, y: 1.8, w: 6, h: 4.5, lineSpacing: 32 });

    // Right: Image
    if (visual) {
        s.addImage({ data: visual, x: 7, y: 1.8, w: 5.5, h: 4 });
    } else {
        s.addShape(pptx.ShapeType.rect, { x: 7, y: 1.8, w: 5.5, h: 4, fill: { color: 'F8FAFC' }, line: { color: 'CBD5E1' } });
        s.addText(slide.visualPrompt, { x: 7.5, y: 3.5, w: 4.5, fontSize: 11, color: '94A3B8', align: 'center', italic: true });
    }

    // Notes
    s.addNotes(slide.speakerNotes);
};